### ISSUE TITLE
Missing list.H file

### ISSUE THREAD

**Issue by ymg2007** [mrklein/windDrivenRain#1]
Hi,mrklein.
I am trying to compile windDrivenRain source code with blueCFD based OpenFOAM 5.x. But after run wmake , it showed a fatal error
**fatal error: List.H: No such file or directory**

![image](https://user-images.githubusercontent.com/24608776/60394283-6a085580-9b54-11e9-9523-a346c95dc07f.png)
Would you mind to help me fix it?

**Comment by mrklein** [comment]
Hi,

I will take a look as soon as I get access to my Windows laptop (though I do not know much about Windows and blueCFD).

In your output paths look rather strange, they all start from `/home/ofuser`. Maybe it is normal under Windows, yet on Linux and macOS, it is not `ofuser` but real user name (`minggang` in your case).

**Comment by ymg2007** [comment]
Thanks for your reply. I am working on Windows 10. The path is the location zip file downloaded from github. I have a suggestion for you. Would you like to record the compiling process? It will help me a lot

**Comment by mrklein** [comment]
Everything turned out to be simpler. In blueCFD distribution there is no List.H file (there it is called List.T.H). Fortunately List header is included indirectly in updateValues.H, so there is no need to in separate include line.

So you can either remove include line manually, or download code once again, I have fixed issue with compilation on Windows in c4b6a267f63588da47154ec46f6d6b44a612ac95.
